apiVersion: apps/v1
kind: Deployment
metadata:
  name: shah-deployment
  labels:
    app: deploy-hello-openshift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-hello-openshift
  template:
    metadata:
      labels:
        app: app-hello-openshift
    spec:
      containers:
      - name: container-hello-openshift
        image: image-registry.openshift-image-registry.svc:5000/shah/hello-openshift
        env:
          # learn about the downward api https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api
        - name: HELLO
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: web
          containerPort: 8090
          protocol: TCP